name: aws_cloudwatch
description: An easy, lightweight, and convenient way to reliably send logs to AWS CloudWatch.
version: 0.4.2
homepage: https://github.com/Zsmerritt/Flutter_AWS_CloudWatch

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  aws_request: ^0.2.0 # Make request to AWS
  synchronized: ^3.0.0 # Synchronize requests to ensure valid keys
  universal_io: ^2.0.0 # Web support\

dev_dependencies:
  test: ^1.16.0