name: aws_cloudwatch
description: An easy, lightweight, turnkey solution for logging with AWS CloudWatch
version: 0.5.7+2
homepage: https://github.com/Zsmerritt/Flutter_AWS_CloudWatch

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  aws_request: ^0.4.0 # Make request to AWS
  synchronized: ^3.0.0 # Synchronize requests to ensure valid keys
  http: ^0.13.0 # Http package for parsing AWS responses correctly on Multiple Platforms
  crypto: ^3.0.0 # Message hashes used to collate split messages

dev_dependencies:
  test: ^1.16.0